### PR TITLE
Fixes #78 #99 #51 Fix build issues on Travis and Appveyor

### LINKED ISSUE #78: Apveyor fails because pywbem package requires non-Windows version of M2Crypto
The approach how the "pywbem" package specifies its prerequisite packages is by means of a complex setup.py, which takes care of pulling in"M2Cryto" on non-Windows and "M2CryptoWin32/64" on Windows. Its wheel archive does not makes that distinction and pulls in "M2Crypto" for all platforms. This can also be seen on Pypi: The dependencies of "pywbem" only mention "M2Crypto" without any platform marker.

This issue basically prevents pywbem to be specified as a dependent package on Windows.

This also the reason Appveyor for "pywbemtools" fails.

I could not find a place in the appveyor.yml to logically turn it off so the easiest was just to remove the webhook from github for the moment.

 https://ci.appveyor.com/api/github/webhook

Reset this into the repository when we want to make this work again

### PR DESCRIPTION
**Pull request by KSchopmeyer**
This was created to test some options when travis did not run.  The issue turned out to be that travis was not active any more.  That was fixed in travis.  However, this pr does try to bring pywbemcli .travis.yml in line with the pywbem file.

NOTE: It will not execute until either we cherry-pic pr #98 or it is merged and this pr rebased.  I am not going to update this one yet.

QUESTION: Is this correct update to yml Andy since you are the expert.

### CODE REVIEW

**Comment by andy-maier** [comment]
I have triggered Travis with an amend + force-push (no content change) to see whether it runs fine.

**Comment by andy-maier** [comment]
Karl, I cannot set you as the reviewer of this PR (probably because you created it), but please review the changes that I made to it.

**Comment by KSchopmeyer** [comment]
1 Forget my comment about the help... program on slack this morning.  I misread that.

2. You know so much more about the details of the requirements, etc. that I can only follow and make minor critique and this point I did not really have even any minor critique.

**Comment by andy-maier** [comment]
We need to support remaking that rst file in the CI runs, because it is (and should be) part of the make tree.

If we want to use the version of pywbemcli that is in the repo, then it cannot be any form of a "pywbemcli" shell command, because that command is only created by the package installation (and then not found on Windows, currently). Instead, it will need to be an invocation of "python pywbemcli/cli.py" or something similar. We could change the click_help_capture.py script to do the invocation that way, which removes the dependency on the installation functioning.

However, we still need to get the installation functioning at some point.

**Comment by andy-maier** [comment]
I have created issue #103 for the issue that pywbemcli is not found on Windows, and there are now Todo markers in the code where there are circumventions of that issue (i.e. `TODO #103`).

The entiere `make test` has been disabled when running on Appveyor. It is active when running on a local Windows that is not Appveyor, so it can be debugged.

**Comment by andy-maier** [comment]
As far as I'm concerned, we can merge this PR. Issue #103 is open for the remaining issue of pywbemcli not found on Windows.

**Comment by andy-maier** [comment]
We agreed to merge this one, once it passes.

**Pull request merged**
