### PR TITLE
Fixes #518: Added support for adjusting help output width to terminal width

### LINKED ISSUE #518: Width of help output is constant and ignores terminal width
Invoking the `--help` option at any command level including globally creates output that is alway 78 characters wide, independent of the current width of the terminal. Click claims that it adjusts the output to the terminal width, but as of click 7.1.1 that is not the case.

The width can be set explicitly via Context attribute `terminal_width`.

### PR DESCRIPTION
**Pull request by andy-maier**
See commit message.

### CODE REVIEW

**Comment by andy-maier** [comment]
Waiting for PR #520 to be merged.

**Comment by andy-maier** [comment]
Click does not honor the terminal width at all, if context.terminal_width is None, not even initially. I think this is a bug in Click, but I did not investigate further after I saw how convoluted the logic there is.

The way we specify the terminal width only works initially, so unless something changes in Click, dynamic changes of terminal width will not be honored.

My suggestion is to go with this PR as it is, because it improves the situations for most cases. We can leave a dynamic reaction to the terminal width for the future.

**Comment by KSchopmeyer** [comment]
I think we could make the more dynamic change work (how many hours have I spent digging around in click) but not a big issue.  A agree and approve this pr.

**Comment by andy-maier** [comment]
Update: It turns out that with the help texts now depending on the terminal width, that we need to be careful when re-creating the docs/pywbemcli/cmdshelp.rst file. Experiments show that the terminal width that needs to be used to re-create that file in the same formatting as currently, is 78.

**Pull request merged**
