### PR TITLE
Rewrite the methods that persist the repo of connections

### PR DESCRIPTION
**Pull request by KSchopmeyer**
This is a code cleanup to create a class for managing the repository
of connections in  place of prototype separate functions.  It added the class
ConnectionRepository and removed the separate methods

See commit message for details of all changes.

### CODE REVIEW

**Comment by KSchopmeyer** [comment]
Failure in latest test is:

wget -q https://raw.githubusercontent.com/pywbem/pywbem/master/pywbem_os_setup.sh
chmod 755 pywbem_os_setup.sh
wget -q https://raw.githubusercontent.com/pywbem/pywbem/master/pywbem_os_setup.bat
chmod 755 pywbem_os_setup.bat
cmd /c pywbem_os_setup.bat install
pywbem_os_setup.bat: Current Python is: Version 2, 32-bit
pywbem_os_setup.bat: Installing OS-level prerequisite packages for install on platform Windows_native ...
pywbem_os_setup.bat: Swig is already installed ... skipping
pywbem_os_setup.bat: Curl is already installed ... skipping
pywbem_os_setup.bat: Grep is already installed ... skipping
pywbem_os_setup.bat: Installing Win32OpenSSL-1_1_0j ...
curl -o Win32OpenSSL-1_1_0j.exe -sSL https://slproweb.com/download/Win32OpenSSL-1_1_0j.exe --retry 3 --retry-connrefused --retry-delay 10
grep "^<html>" Win32OpenSSL-1_1_0j.exe
chmod 755 Win32OpenSSL-1_1_0j.exe
pywbem_os_setup.bat: ACL permissions of Win32OpenSSL-1_1_0j.exe:
Win32OpenSSL-1_1_0j.exe NULL SID:(DENY)(Rc,S,REA,X,DC)
                        APPVYR-WIN\appveyor:(F)
                        APPVYR-WIN\None:(RX)
                        NT AUTHORITY\SYSTEM:(RX,W)
                        BUILTIN\Administrators:(RX,W)
                        BUILTIN\Users:(RX)
                        Everyone:(RX)
Successfully processed 1 files; Failed processing 0 files
Win32OpenSSL-1_1_0j.exe /silent /verysilent /suppressmsgboxes /dir="C:\OpenSSL-1-1-0j-Win32"
The system cannot execute the specified program.
pywbem_os_setup.bat: Error: Command returned rc=1

**DISCUSSION**

**It is failing the execution of Win32OpenSSL-1_1_1_oj.exe**

**Comment by andy-maier** [comment]
Reason is they released 1.1.0k. Every time they make a release, they remove the previously released version (1.1.0j).

**Comment by andy-maier** [comment]
I have created https://github.com/pywbem/pywbem/issues/1754 to fix this.

**Comment by andy-maier** [comment]
This will be fixed in pywbem 0.14.3, to be released in the next couple of days.

**Comment by andy-maier** [comment]
pywbem 0.14.3 has been released to Pypi. If you upgrade the minimum version of pywbem that is pulled in to pywbemtools, the issue should be solved.

**Pull request merged**
