### PR TITLE
Fixes #634: Added value-mapped string to properties in instance table output

### LINKED ISSUE #634: Need an output option for displaying Value/Valuemap information
I would like an option on output for displaying VALUE information instead of, or in addition to, VALUEMAP information. SNIA uses the Dedicated property on ComputerSystem. But you need to have a cheat sheet handy to tell you Dedicated="24" is a NAS Head, Dedicated="25" is a Self-contained NAS and Decidated="16" is a File Server. Similarly, you need a cheat sheet to tell you that HealthState="5" means "OK".
For demo's I can get the class to show the cheat sheet, but Dedicated has over 40 values. 24 and 25 are pretty much in the middle. Manually coordinating what a number corresponds to is not all that easy.

### PR DESCRIPTION
**Pull request by andy-maier**
**Update: For latest status, see the last comments of this PR**

Ready for initial use and review.

The use of valuemap/values is always enabled when displaying instances in a table format and when the WBEM server supports class operations, so there is no option to enable or disable it.
The properties that are integer-typed and that have a valuemapping defined or inherited in the creation class of the instance are displayed with the Values value in parenthesis after the integer value.

Example with the changes from this PR, that added a "gender" property with value-mapped values for male and female:
```
$ pywbemcli -m tests/unit/simple_assoc_mock_model.mof -o table instance enumerate TST_Person
Instances: TST_Person
+------------+------------+------------------+-----------+
| name       | gender     | secondProperty   | counter   |
|------------+------------+------------------+-----------|
| "Gabi"     | 1 (female) |                  |           |
| "Mike"     | 2 (male)   |                  |           |
| "Saara"    | 1 (female) |                  |           |
| "Sofi"     | 1 (female) |                  |           |
| "Gabisub"  | 1 (female) | "four"           | 4         |
| "Mikesub"  | 2 (male)   | "one"            | 1         |
| "Saarasub" | 1 (female) | "two"            | 2         |
| "Sofisub"  | 1 (female) | "three"          | 3         |
+------------+------------+------------------+-----------+
```

Discussion points:
* Do we need an option to enable or disable the value-mapping output?
* If the WBEM server does not support class operations, do we expect a warning or just silently not showing value-mapping output?
* Do we also need it for string-typed properties?
Mike has provided his views on these discussion points further down.

Limitation: This PR limits the support to scalar elements. Array elements are displayed as normal, i.e. without the value-mapped value in parenthesis.

### CODE REVIEW

**Comment by FarmerMike252** [comment]
On your discussion points I would say:

- Do we need an option to enable or disable the value-mapping output? NO
- If the WBEM server does not support class operations, do we expect a warning or just silently not showing value-mapping output? JUST SILENTLY SHOW VALUEMAP
- Do we also need it for string-typed properties? NO

**Comment by andy-maier** [comment]
@FarmerMike252 In your answer to the second question, did you actually mean to say "JUST SILENTLY **NOT** SHOW VALUEMAP"?

If so, then the PR that is up is in tune with your answers.

**Comment by KSchopmeyer** [comment]
I was thinking of just the values rather than values and maps.  with option to show the maps or maps and values.  I don't have strong reason however since this is all new

**Comment by FarmerMike252** [comment]
I am fine with just showing the value/valuemap pair. However, my testing shows that it only works sometimes. It worked on CIM_RegisteredProfile instances, but when I tested it on CIM_ComputerSystem the translation was only done on EnabledState.
My test output is:
pywbemcli> instance enumerate CIM_ComputerSystem --pl InstanceID,CreationClassName,Name,Dedicated,OperationalStatus,HealthState,EnabledS
tate
Instances: CIM_ComputerSystem
+--------------+-------------+----------------------+----------------------+--------------------+---------------------+
| InstanceID   | Dedicated   | CreationClassName    | Name                 | EnabledState       | OperationalStatus   |
|--------------+-------------+----------------------+----------------------+--------------------+---------------------|
| "CS0"        | 3, 15       | "CIM_ComputerSystem" | "ACME+CF2A509130008" | 5 (Not Applicable) | 2, 32769            |
|              |             |                      | "9"                  |                    |                     |
| "CS_A"       | 12          | "CIM_ComputerSystem" | "ACME+CF2A509130008" | 2 (Enabled)        | 2, 32769            |
|              |             |                      | "9+SP_A"             |                    |                     |
| "CS_B"       | 12          | "CIM_ComputerSystem" | "ACME+CF2A509130008" | 2 (Enabled)        | 2, 32769            |
|              |             |                      | "9+SP_B"             |                    |                     |
+--------------+-------------+----------------------+----------------------+--------------------+---------------------+
pywbemcli> instance enumerate CIM_ComputerSystem --pl InstanceID,CreationClassName,Name,Dedicated,OperationalStatus
Instances: CIM_ComputerSystem
+--------------+-------------+----------------------+---------------------------+---------------------+
| InstanceID   | Dedicated   | CreationClassName    | Name                      | OperationalStatus   |
|--------------+-------------+----------------------+---------------------------+---------------------|
| "CS0"        | 3, 15       | "CIM_ComputerSystem" | "ACME+CF2A5091300089"     | 2, 32769            |
| "CS_A"       | 12          | "CIM_ComputerSystem" | "ACME+CF2A5091300089+SP_" | 2, 32769            |
|              |             |                      | "A"                       |                     |
| "CS_B"       | 12          | "CIM_ComputerSystem" | "ACME+CF2A5091300089+SP_" | 2, 32769            |
|              |             |                      | "B"                       |                     |
+--------------+-------------+----------------------+---------------------------+---------------------+
pywbemcli> instance enumerate CIM_ComputerSystem --pl InstanceID,CreationClassName,Name,Dedicated
Instances: CIM_ComputerSystem
+--------------+-------------+----------------------+----------------------------+
| InstanceID   | Dedicated   | CreationClassName    | Name                       |
|--------------+-------------+----------------------+----------------------------|
| "CS0"        | 3, 15       | "CIM_ComputerSystem" | "ACME+CF2A5091300089"      |
| "CS_A"       | 12          | "CIM_ComputerSystem" | "ACME+CF2A5091300089+SP_A" |
| "CS_B"       | 12          | "CIM_ComputerSystem" | "ACME+CF2A5091300089+SP_B" |
+--------------+-------------+----------------------+----------------------------+
pywbemcli>

**Comment by FarmerMike252** [comment]
Andy, yes I meant "JUST SILENTLY NOT SHOW VALUEMAP". However, look at my previous comment. I don't understand why we are not getting the output on Dedicated and OperationalStatus.

**Comment by andy-maier** [comment]
I'll look into it. It is definitely not intended :-) They are both arrays, maybe there is a bug.

**Comment by andy-maier** [comment]
It turns out that `pywbem.ValueMapping` only supports scalar integer-typed properties: https://github.com/pywbem/pywbem/blob/master/pywbem/_valuemapping.py#L714.

The reason this did not fail with the array properties, is that in my use of it in pywbemtools, I was unintendedly consistent with that, by using a type check that did not match for arrays: https://github.com/pywbem/pywbemtools/blob/andy/valuemap/pywbemtools/pywbemcli/_common.py#L1469

The action is to add support for array elements to `pywbem.ValueMapping` (see new issue ), and to accept arrays in the code in pywbemtools. It seems to me that that will cause pywbemtools to have pywbem 1.0.0 as a minimum version.

**Comment by andy-maier** [comment]
It turned out that `pywbem.ValueMapping` did support array-typed CIM elements all along, it was just not documented. What was missing was an ability of `ValueMapping.tovalues()` to pass in a list or tuple of element values in a single call, so that a caller would not need to distinguish the caes of scalar and array typed elements. This ability will be added in pywbem 0.17.3 and 1.0.0b2. However, pywbemtools does not depend on this new ability because it processes one property at a time, and thus always invokes `ValueMapping.tovalues()` with a single value (for both the scalar-typed and array-typed elements).

As a result, this PR now works for both scalar-typed and array-typed properties, for all supported versions of pywbem.

**Comment by andy-maier** [comment]
Merged it. Karl agrees that for now, we won't add options to enable or disable the behavior. If there are issues with this change, or requests for new functionality around it, please open a new issue.

**Pull request merged**
