### PR TITLE
Fixes #895: Implement statistics server-show

### LINKED ISSUE #895: Extend statistics to get WBEM server detailed operation statistics from the server.
Issue #588 defines the issue and pr #894 the changes to clean up statistics.  However, one item is left open, getting and presenting statistics from the server, specifically the CIM_StatisticalInformation class.

That presents the server summary of requests and responses for those servers that implement the capability.

This issue proposes adding that capability.  Note that the privious pr actually defines the command but documents it as not implemented.

### PR DESCRIPTION
**Pull request by KSchopmeyer**
Implements the command to get statistical data from the server
and display it. This displays the data from the WBEM server
CIM_CIMOMStatisticalData class as a table showing the
number of operations and statistics for those operations (size,
server execution time and provider execution time) as a table
with data for each operation that has non-zero number of
operations.

Example of the report for discussion

```

WBEM server CIM Operation Statistical Data
+-------------+--------------+--------------+---------------+---------------+------------------------+
|   Operation |       Server |     Provider |       Request |      Response | Operation Name         |
|       Count |   time(usec) |   Time(usec) |   size(bytes) |   size(bytes) |                        |
|-------------+--------------+--------------+---------------+---------------+------------------------|
|          34 |        459.2 |          0   |         379.5 |       14505.3 | EnumerateClassNames    |
|          45 |       7719.4 |       3264.8 |         381.3 |        3739.4 | EnumerateInstanceNames |
|          62 |       2241.3 |         73.2 |         384.9 |        2449.1 | EnumerateInstances     |
|           4 |        229.8 |          0   |         582   |        4339   | GetClass               |
|           8 |        471.4 |         38.1 |         862   |        3128   | GetInstance            |
|           8 |        884.9 |         25.6 |        3523   |         376.4 | ModifyInstance         |
|           5 |       7372.6 |          0   |         595.2 |        3192   | OpenEnumerateInstances |
+-------------+--------------+--------------+---------------+---------------+------------------------+

### CODE REVIEW

**Comment by KSchopmeyer** [comment]
**DISCUSSION:** Not sure what the latest failure with python 3.4 means

**Comment by KSchopmeyer** [comment]
DISCUSSION: Next stepts with statistics:

1. We are now able to produce a report of statistics being kept by the server.  Limitations:

  a. Not validating statistics counts against the statistics kept by client.  We are using instances captured from pegasus to produce the report and so validating that we can output a valid statistics response.  This is probably an end-end test against container to validate counts and estimated times/sizes. 
  b. Still trying to explain why pegasus produces the statistics on the root/cimv2 namespace.  Our tests are producing them on the interop namespace.

NOTE: This is the simplest output of statistics and does not go into futher issues of more complete statistics, statistics over specifiec times from server.

DISCUSSION: Can we commit this and then go on to next steps.

**Comment by KSchopmeyer** [comment]
TODO: Align the headers between the pywbemcli stats and server statistics.

**Comment by andy-maier** [comment]
I have some more info on the server statistics returned by my local pegasus container:

- With the current state of the PR, "statistics server-show" now displays statistics as expected.

- Enumerating CIM_StatisticalData instances in root/cimv2 with DeepInheritance returns the expected instances for each operation, like this:
```
$ pywbemcli -n local instance enumerate CIM_StatisticalData --di -n root/cimv2
instance of CIM_CIMOMStatisticalData {
   InstanceID = "OpenAssociators27";
   OperationType = 1;
   OtherOperationType = "OpenAssociators";
   NumberOfOperations = 0;
   CimomElapsedTime = "00000000000000.000000:000";
   ProviderElapsedTime = "00000000000000.000000:000";
   RequestSize = 0;
   ResponseSize = 0;
   Description = "CIMOM performance statistics for CIM request ";
   Caption = "CIMOM performance statistics for CIM request";
};
```

I do not know why server-show displayed an empty result for me in earlier attempts.

The earlier instances I perceived as incorrect were the resault of a combination of enumerating the superclass and not specifying DeepInheritance, like in this example:
```
$ pywbemcli -n local instance enumerate CIM_StatisticalData -n root/cimv2
instance of CIM_CIMOMStatisticalData {
   Caption = "CIMOM performance statistics for CIM request";
   Description = "CIMOM performance statistics for CIM request ";
   InstanceID = "SetProperty19";
};
```

**Comment by andy-maier** [comment]
With the comments above, and with PR #902 fixing the py34 issue, this PR just needs to be rebased and thewn is ready to be merged.

**Review by andy-maier — APPROVED** [review]
Please rebase on master, otherwise approved.

**Comment by andy-maier** [comment]
**DISCUSSION:** Karl, please review the recent comments on this PR to see whether you agree that it is ready to be merged.

**Comment by KSchopmeyer** [comment]
I agree that it is ready to be merged.

**Comment by andy-maier** [comment]
Karl agreed in the Slack channel to merge it.

**Pull request merged**
