### PR TITLE
Ks/#1023/logging change interactive

### PR DESCRIPTION
**Pull request by KSchopmeyer**
Adds logic to enable, disable and modify the log configuration for each interactive --log option

Note: Added a verbose msg output showing the --log change.

### CODE REVIEW

**Comment by andy-maier** [comment]
See the deepcopy errors on py27 and py34. There is your lock error again.
I wonder why there is a `thread.lock` object on the `pywbem_server` object. Also, is the `_io.TextIOWrapper` object caused by logging?
Finally, I find it strange that `deepcopy()` issues error messages that use the terms "pickle" and "serialize".

**Comment by KSchopmeyer** [comment]
1. Apparently deepcopy actually uses pickle methods which explains the pickle messages.   

2.  The Threadlock comes from the logger and only on old python versions so I can assume that there was something in these vesions of the logger where locks were set into the copiable data but that was moved, modified, etc. somewhere in python logger because of this type of issue.

**Review by andy-maier — APPROVED** [review]
Please rebase and resolve the merge conflict in changes.rst. Otherwise, approved.

**Comment by KSchopmeyer** [comment]
Issues from  in merge resolved.

**Comment by andy-maier** [comment]
Needs It still contains a commit named after a PR that is already merged. Please verify whether you want the change from that commit, or not.

**Pull request merged**
