### PR TITLE
Fixes #817: Adds --details option to class tree display

### LINKED ISSUE #817: Extend the class tree command to optionall provide extra class information
Extend the class tree command to provide extra information about the classes shown in the tree.  This would include:

1. The Version quaalifier for the class since this is pertinent to the tree and it is not clear from the particular class mof definition what the effective version is since the version of classes higher in the hierarchy might have different versions.

2. Some core indication information including whether the class is Association, Indication, or Abstract.

The following is a proposed format:

```
root
 +-- CIM_Foo (Ver=2.30.0)
 |   +-- CIM_Foo_sub (Ver=2.31.0)
 |       +-- CIM_Foo_sub_sub (Ver=2.20.1)
 +-- CIM_Foo_no_version ()
 +-- CIM_Indication (Abst,Ind Ver=2.24.0)
 +-- CIM_Indication_no_version (Abst,Ind)
 +-- TST_Lineage (Assoc Ver=2.20.1)
 +-- TST_Lineage_no_version (Assoc)

### PR DESCRIPTION
**Pull request by KSchopmeyer**
See issue # 817 for example of output and commit for details of changes.

Note that this pr made extensive changes to the code in _displaytree.py (largely rewriting it to make the code more readable.

See the issue for output examples.

### CODE REVIEW

**Review by andy-maier — CHANGES_REQUESTED** [review]
My only comment is to use the full qualifier names, e.g. blank separated.

**Comment by KSchopmeyer** [comment]
We are getting the following error on the windows builds.


Run make build
del /f /q pip_upgrade_py3.9.done
Could Not Find D:\a\pywbemtools\pywbemtools\pip_upgrade_py3.9.done
python -m pip install -c minimum-constraints.txt pip
DEPRECATION: Constraints are only allowed to take the form of a package name and a version specifier. Other forms were originally permitted as an accident of the implementation, but were undocumented. The new implementation of the resolver no longer supports these forms. A possible replacement is replacing the constraint with a requirement.. You can find discussion regarding this at https://github.com/pypa/pip/issues/8210.
ERROR: Links are not allowed as constraints
WARNING: You are using pip version 20.3; however, version 20.3.3 is available.
You should consider upgrading via the 'C:\hostedtoolcache\windows\Python\3.9.0\x64\python.exe -m pip install --upgrade pip' command.
mingw32-make: *** [Makefile:406: pip_upgrade_py3.9.done] Error 1
Error: Process completed with exit code 1.

**Comment by KSchopmeyer** [comment]
Update completed to show complete association names.

**Comment by andy-maier** [comment]
I rebased this on master to pick up the Windows fix.

**Pull request merged**
